version: "3.8"

services:
  backend:
    build: ./v1_backend
    expose:
      - "4000"
    volumes:
      - ./v1_backend/faces.db:/app/faces.db

  frontend:
    build: ./v1_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
