version: "3.8"

services:
  backend:
    build: ./v1_backend
    ports:
      - "4000:4000"
    volumes:
      - ./v1_backend/faces.db:/app/faces.db

  frontend:
    build: ./v1_frontend
    command: ["true"]   # build-only container

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./v1_frontend/build:/usr/share/nginx/html:ro
